language: node_js
node_js:
  - 16
#dist: jammy
#addons:
#  apt:
#    sources:
#      - sourceline: 'deb https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1   # prevent gcloud from prompting
    - CLOUDSDK_PYTHON=/opt/pyenv/versions/3.11.5/bin/python3.11

cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - "/opt/pyenv/versions/3.11.5"

before_install:
  - openssl aes-256-cbc -K $encrypted_fce61e3da44a_key -iv $encrypted_fce61e3da44a_iv -in travis-deploy-gcp-key.json.enc -out travis-deploy-gcp-key.json -d
#  - if [ ! -d "/opt/pyenv/versions/3.11.5" ]; then pyenv install 3.11.5; fi
  - pyenv install -f 3.11.5
  - pyenv global 3.11.5
  - gcloud auth activate-service-account --key-file=travis-deploy-gcp-key.json
  - gcloud auth configure-docker        # enable "docker push" to gcr
  - gcloud config set project "$PROJECT"

script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - |
    set -ex;
    npm install && \
    npm run build && \
    gcloud app deploy $APP_YAML_NAME
    set +x